### ISSUE TITLE
Problems with personal_unlockAccount

### ISSUE THREAD

**Issue by rickenbb** [xf00f/web3x#52]
Hi all,

first of all, cool project you have here!

Recently I faced a potential bug. When trying to use the personal_unlockAccount method, I get an error saying the method does not exist.
A bit of investigation showed that somewhere along the way the method and parameters seem to disappear. 
Unfortunately I have not yet had the time to dig in deep enough to exactly pinpoint the issue.
The problem occurs both with websocket and HTTP providers (those are the ones I tried).

Can you reproduce the error? Is there a workaround for this? 

 
<code>Error: The method _ does not exist/is not available
    at provider.send (/home/benjamin/Desktop/ONECLICK/one-click-server/node_modules/web3x/providers/legacy-provider-adapter.js:37:35)
    at module.exports.request.onreadystatechange (/home/benjamin/Desktop/ONECLICK/one-click-server/node_modules/web3x/providers/http.js:73:17)
    at emitOne (events.js:116:13)
    at module.exports.emit (events.js:211:7)
    at module.exports.EventTarget.dispatchEvent (/home/benjamin/Desktop/ONECLICK/one-click-server/node_modules/node-http-xhr/lib/node-event-target.js:114:8)
    at module.exports.NodeHttpXHR._setReadyState (/home/benjamin/Desktop/ONECLICK/one-click-server/node_modules/node-http-xhr/lib/index.js:339:8)
    at module.exports.onEnd (/home/benjamin/Desktop/ONECLICK/one-click-server/node_modules/node-http-xhr/lib/index.js:482:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)</code>

**Comment by xf00f** [comment]
This should be fixed in release `v4.0.0`.

**Comment by rickenbb** [comment]
Hi @xf00f ,

thanks for the reply.
Looking forward to it!
